### PR TITLE
Added Support For Simple Voice Chat

### PR DESCRIPTION
**Pull request by Moyettes**
I ported this mod to paper and I added [Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat) to my port so I wanted to add the same features to the mod to keep them somewhat in Parity. Here is my port for Paper https://github.com/Bryan1029384756/PaperRecorder

To use new feature for the mod please download the [Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat) mod for fabric and install in the plugins folder and Mod will take care of the rest. To hear the voices in the [Replay Mod](https://modrinth.com/mod/replaymod) please download [Replay Voice Chat](https://modrinth.com/mod/replay-voice-chat). This feature is optional and does not force the users to get Simple Voice Chat to use Server side replay recorder.

### CODE REVIEW

**Comment by thecolonel63** [comment]
Hi! This looks promising, but I'll have to run some testing later to ensure this works properly before I decide if I can merge the commit.

**Comment by mattymatty97** [comment]
by the look of the code you're sending all audio packets to all active recorders always.
that will quickly make the file sizes explode. it is needed to apply some pruning in order to only send the packets to the recorders that can hear them

- also i saw you're using the save() method of the recorders, it is better if you use the onPacket one instead.
- another note is that VoiceRecorder is not an extension of a ReplayRecorder but a Utility class so it should be moved to it's appropriate package

**Comment by Moyettes** [comment]
Your right, i only did save() because that's how another mod did it and they skipped the onPacket. I originally had it on onPacket but changed it because audio issues but that has been resolved. onSound has a sender and that's basically the clients audio. So what ill do is when onSound is called I'm going to get the sender and save that packet to their recording. onEntitySound has a Receiver connection (and I belive the others one also but I need to test. Right now I just got a second account to test with 2 players) that I can get and will be able to save to their recorder. Ill looks at it later today when I get out of work. Packaged moved to the Util class. Im new to all of this still but learning as I'm going. (Going to do some more testing)

**Comment by Moyettes** [comment]
Updated to only send packets to players that are nearby. I think having the max distance to the server view distance is fine but I'll probably add it to the config so they can better modify what they want. In the replay they can hear a lot further than they can ingame but I wanted to get voices from players farther than the default 32 blocks in Simple Voice Chat, an opinion would be nice if we should only get the same voices from within the default voice radius or all voice's in possible loaded chunks nearby the player, like how it is setup right now. The only thing I can't get working is the region recording. Still working on it but take a look when you guys get the chance

**Comment by Moyettes** [comment]
So far I was able to get Voice Recording to work for player recording, I was not able to make any progress with region recording. I also updated the config to have:

#The range from the player that is being recorded that it will pick up other players voices in the replay
voice_recording_range: 48  

#enable or disable the whole voice recording
voice_recording_enabled: false

**Comment by Moyettes** [comment]
Ok finished. Everything works now. Player Voice Recording and Region Voice Recording all work. Just give it a try when you have a chance and let me know if I missed anything.

**Pull request closed without merging**
